version: 2
updates:
  - package-ecosystem: cargo
    directory: /application
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /domain
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /infrastructure
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
