ARG NODE_VERSION=23

FROM node:${NODE_VERSION}-slim AS base
ENV NODE_ENV=development
WORKDIR /app

FROM base AS build
COPY --link package.json package-lock.json ./
RUN npm ci

FROM base
COPY --from=build /app/node_modules /app/node_modules
CMD ["npm", "run", "dev"]
