volumes:
  pg_data:
  node_modules:

services:
  frontend:
    profiles:
      - prod
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: ${API_URL:-http://backend:4000}

  frontend-dev:
    profiles:
      - dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    environment:
      API_URL: ${API_URL:-http://host.docker.internal:4000}
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

#  backend:
#    profiles:
#      - prod
#    build:
#      context: ./server
#    ports:
#      - "4000:4000"
#    environment:
#      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/postgres}

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PW:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
