[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.13.1", features = ["v7"] }
chrono = "0.4.39"
serde = { version = "1.0.217", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde", "uuid/serde"]
