name: Rust

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - application/**/*
      - domain/**/*
      - infrastructure/**/*
      - server/**/*
      - Cargo.toml
      - .github/workflows/rust.yml

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-cache"
      - run: cargo fmt --check --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-cache"
      - run: cargo clippy --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-cache"
      - run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-cache"
      - run: cargo test --verbose
