name: Rust

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - application/**/*
      - domain/**/*
      - infrastructure/**/*
      - server/**/*
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --check --verbose

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
